### ISSUE TITLE
Dependency to BowlingLeagueStructure.sql

### ISSUE THREAD

**Issue by richardbroersma** [TexanInParis/Effective-SQL#1]
Consider adding comment for dependency to BowlingLeagueStructure.sql.

**Comment by DJSteele** [comment]
Sorry, Richard, but of what dependency are you speaking? 

 

Listings.xlsx indicates which listings depend on that sample.

 

Or are you suggesting that we indicate that it’s necessary to run BowlingLeagueStructure.sql before you can run BowlingLeagueData.sql?

 

Doug Steele
My Website <http://www.accessmvp.com/DJSteele> 
My MVP profile <https://mvp.microsoft.com/en-us/mvp/Douglas%20J%20Steele-6961>

**Comment by bclothier** [comment]
Believe he’s referring to the need to run structure before data.

 

Ben

**Comment by richardbroersma** [comment]
Correct,  I noticed that BeerStylesData.sql has the following comment:

-- This requires that the tables from BeerStylesStructure.sql be created
> first.


The other Data SQL files did not include a similar comment.

On Mon, Jun 13, 2016 at 11:03 AM, bclothier <notifications@github.com>
wrote:

> Believe he’s referring to the need to run structure before data.
>
>
>
> Ben
>
>
>
> From: DJSteele <notifications@github.com>
> Reply-To: TexanInParis/Effective-SQL <reply@reply.github.com>
> Date: Monday, June 13, 2016 at 1:00 PM
> To: TexanInParis/Effective-SQL <Effective-SQL@noreply.github.com>
> Subject: Re: [TexanInParis/Effective-SQL] Dependency to
> BowlingLeagueStructure.sql (#1)
>
>
>
> Sorry, Richard, but of what dependency are you speaking?
>
>
>
> Listings.xlsx indicates which listings depend on that sample.
>
>
>
> Or are you suggesting that we indicate that it’s necessary to run
> BowlingLeagueStructure.sql before you can run BowlingLeagueData.sql?
>
>
>
> Doug Steele
> My Website <http://www.accessmvp.com/DJSteele>
> My MVP profile <
> https://mvp.microsoft.com/en-us/mvp/Douglas%20J%20Steele-6961>
>
>
>
>
>
>
>
> From: richardbroersma [mailto:notifications@github.com]
> Sent: Monday, June 13, 2016 13:38
> To: TexanInParis/Effective-SQL
> Subject: [TexanInParis/Effective-SQL] Dependency to
> BowlingLeagueStructure.sql (#1)
>
>
>
> Consider adding comment for dependency to BowlingLeagueStructure.sql.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub <
> https://github.com/TexanInParis/Effective-SQL/issues/1> , or mute the
> thread <
> https://github.com/notifications/unsubscribe/ARep2qKUe6BB-lJDYtQ-gaZe4jwZWv5dks5qLZWFgaJpZM4I0kFc>
> . <
> https://github.com/notifications/beacon/ARep2ick_yYGz5SxCDibAixoB5Ra_eNQks5qLZWFgaJpZM4I0kFc.gif>
>
>
>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/TexanInParis/Effective-SQL/issues/1#issuecomment-225660371>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEHQ7w8_T7Uysva9tAfsQDbuxCcsNqelks5qLZtggaJpZM4I0kFc>
> .
>



-- 
Regards,
Richard Broersma Jr.

**Comment by bclothier** [comment]
Addressed.
