### ISSUE TITLE
Last GROUP BY clause in Listing 5.015.sql

### ISSUE THREAD

**Issue by buzzerrookie** [TexanInParis/Effective-SQL#22]
In PostgreSQL Listing 5.015.sql, I think the last GROUP BY clause can be omitted becasue the subquery is restricted to a single CategoryID.
```
SELECT C.CategoryDescription, P.ProductName, 
  SUM(OD.QuotedPrice * OD.QuantityOrdered) AS TotalSales
FROM Products AS P 
  INNER JOIN Order_Details AS OD 
     ON P.ProductNumber=OD.ProductNumber
  INNER JOIN Categories AS C
     ON C.CategoryID = P.CategoryID
  INNER JOIN Orders AS O
     ON O.OrderNumber = OD.OrderNumber
WHERE O.OrderDate BETWEEN '2015-10-01' AND '2015-12-31'
GROUP BY P.CategoryID, C.CategoryDescription, P.ProductName
HAVING SUM(OD.QuotedPrice * OD.QuantityOrdered) > 
  (SELECT AVG(SumCategory) 
   FROM 
     (SELECT P2.CategoryID, 
       SUM(OD2.QuotedPrice * OD2.QuantityOrdered) 
       AS SumCategory 
      FROM Products AS P2 
      INNER JOIN Order_Details AS OD2 
        ON P2.ProductNumber = OD2.ProductNumber 
      INNER JOIN Orders AS O2
        ON O2.OrderNumber = OD2.OrderNumber
      WHERE P2.CategoryID = P.CategoryID
      AND O2.OrderDate BETWEEN '2015-10-01' AND '2015-12-31'
      GROUP BY P2.CategoryID, P2.ProductNumber) AS S)
ORDER BY CategoryDescription, ProductName;
```

**Comment by TexanInParis** [comment]
Nope, the GROUP BY is required because any column returned by a SELECT that includes one or more aggregate functions must either be the result of an aggregate function or be listed in GROUP BY.  If we didn’t need CategoryID to be returned (it’s required so we can filter it), then the GROUP BY would not be needed - the SUM would be across all rows returned.

John Viescas
TexanInParis

> On Oct 15, 2019, at 04:54, buzzerrookie <notifications@github.com> wrote:
> 

﻿
In PostgreSQL Listing 5.015.sql, I think the last GROUP BY clause can be omitted becasue the subquery is restricted to a single CategoryID.

SELECT C.CategoryDescription, P.ProductName, 
  SUM(OD.QuotedPrice * OD.QuantityOrdered) AS TotalSales
FROM Products AS P 
  INNER JOIN Order_Details AS OD 
     ON P.ProductNumber=OD.ProductNumber
  INNER JOIN Categories AS C
     ON C.CategoryID = P.CategoryID
  INNER JOIN Orders AS O
     ON O.OrderNumber = OD.OrderNumber
WHERE O.OrderDate BETWEEN '2015-10-01' AND '2015-12-31'
GROUP BY P.CategoryID, C.CategoryDescription, P.ProductName
HAVING SUM(OD.QuotedPrice * OD.QuantityOrdered) > 
  (SELECT AVG(SumCategory) 
   FROM 
     (SELECT P2.CategoryID, 
       SUM(OD2.QuotedPrice * OD2.QuantityOrdered) 
       AS SumCategory 
      FROM Products AS P2 
      INNER JOIN Order_Details AS OD2 
        ON P2.ProductNumber = OD2.ProductNumber 
      INNER JOIN Orders AS O2
        ON O2.OrderNumber = OD2.OrderNumber
      WHERE P2.CategoryID = P.CategoryID
      AND O2.OrderDate BETWEEN '2015-10-01' AND '2015-12-31'
      GROUP BY P2.CategoryID, P2.ProductNumber) AS S)
ORDER BY CategoryDescription, ProductName;

**Comment by buzzerrookie** [comment]
But without the last group by in Listing 5.015.sql, I can get the same query result as the query with Listing 5.015.sql.
with the last group by
```
SELECT C.CategoryDescription, P.ProductName, 
  SUM(OD.QuotedPrice * OD.QuantityOrdered) AS TotalSales
FROM Products AS P 
  INNER JOIN Order_Details AS OD 
     ON P.ProductNumber=OD.ProductNumber
  INNER JOIN Categories AS C
     ON C.CategoryID = P.CategoryID
  INNER JOIN Orders AS O
     ON O.OrderNumber = OD.OrderNumber
WHERE O.OrderDate BETWEEN '2015-10-01' AND '2015-12-31'
GROUP BY P.CategoryID, C.CategoryDescription, P.ProductName
HAVING SUM(OD.QuotedPrice * OD.QuantityOrdered) > 
  (SELECT AVG(SumCategory) 
   FROM 
     (SELECT P2.CategoryID, 
       SUM(OD2.QuotedPrice * OD2.QuantityOrdered) 
       AS SumCategory 
      FROM Products AS P2 
      INNER JOIN Order_Details AS OD2 
        ON P2.ProductNumber = OD2.ProductNumber 
      INNER JOIN Orders AS O2
        ON O2.OrderNumber = OD2.OrderNumber
      WHERE P2.CategoryID = P.CategoryID
      AND O2.OrderDate BETWEEN '2015-10-01' AND '2015-12-31'
      GROUP BY P2.CategoryID, P2.ProductNumber) AS S 
GROUP BY CategoryID)
ORDER BY CategoryDescription, ProductName;
```
```
 categorydescription |           productname            | totalsales
---------------------+----------------------------------+-------------
 Accessories         | Cycle-Doc Pro Repair Stand       |  32595.7600
 Accessories         | Dog Ear Aero-Flow Floor Pump     |  15539.1500
 Accessories         | Glide-O-Matic Cycling Helmet     |  23640.0000
 Accessories         | King Cobra Helmet                |  27847.2600
 Accessories         | Viscount CardioSport Sport Watch |  16469.7900
 Bikes               | GT RTS-2 Mountain Bike           | 527703.0000
 Bikes               | Trek 9000 Mountain Bike          | 954516.0000
 Car racks           | Ultimate Export 2G Car Rack      |  31014.0000
 Clothing            | StaDry Cycling Pants             |   8641.5600
 Components          | AeroFlo ATB Wheels               |  37709.2800
 Components          | Cosmic Elite Road Warrior Wheels |  32064.4500
 Components          | Eagle SA-120 Clipless Pedals     |  17003.8500
 Skateboards         | Viscount Skateboard              | 196964.3000
 Tires               | Ultra-2K Competition Tire        |   5216.2800
(14 rows)
```

without the last group by
```
SELECT C.CategoryDescription, P.ProductName, 
  SUM(OD.QuotedPrice * OD.QuantityOrdered) AS TotalSales
FROM Products AS P 
  INNER JOIN Order_Details AS OD 
     ON P.ProductNumber=OD.ProductNumber
  INNER JOIN Categories AS C
     ON C.CategoryID = P.CategoryID
  INNER JOIN Orders AS O
     ON O.OrderNumber = OD.OrderNumber
WHERE O.OrderDate BETWEEN '2015-10-01' AND '2015-12-31'
GROUP BY P.CategoryID, C.CategoryDescription, P.ProductName
HAVING SUM(OD.QuotedPrice * OD.QuantityOrdered) > 
  (SELECT AVG(SumCategory) 
   FROM 
     (SELECT P2.CategoryID, 
       SUM(OD2.QuotedPrice * OD2.QuantityOrdered) 
       AS SumCategory 
      FROM Products AS P2 
      INNER JOIN Order_Details AS OD2 
        ON P2.ProductNumber = OD2.ProductNumber 
      INNER JOIN Orders AS O2
        ON O2.OrderNumber = OD2.OrderNumber
      WHERE P2.CategoryID = P.CategoryID
      AND O2.OrderDate BETWEEN '2015-10-01' AND '2015-12-31'
      GROUP BY P2.CategoryID, P2.ProductNumber) AS S)
ORDER BY CategoryDescription, ProductName;
```
```
 categorydescription |           productname            | totalsales
---------------------+----------------------------------+-------------
 Accessories         | Cycle-Doc Pro Repair Stand       |  32595.7600
 Accessories         | Dog Ear Aero-Flow Floor Pump     |  15539.1500
 Accessories         | Glide-O-Matic Cycling Helmet     |  23640.0000
 Accessories         | King Cobra Helmet                |  27847.2600
 Accessories         | Viscount CardioSport Sport Watch |  16469.7900
 Bikes               | GT RTS-2 Mountain Bike           | 527703.0000
 Bikes               | Trek 9000 Mountain Bike          | 954516.0000
 Car racks           | Ultimate Export 2G Car Rack      |  31014.0000
 Clothing            | StaDry Cycling Pants             |   8641.5600
 Components          | AeroFlo ATB Wheels               |  37709.2800
 Components          | Cosmic Elite Road Warrior Wheels |  32064.4500
 Components          | Eagle SA-120 Clipless Pedals     |  17003.8500
 Skateboards         | Viscount Skateboard              | 196964.3000
 Tires               | Ultra-2K Competition Tire        |   5216.2800
(14 rows)
```

**Comment by TexanInParis** [comment]
Ah, I didn’t realize in the example you gave me that you had *already* removed the offending GROUP BY.  You are correct, that GROUP BY just before the ORDER BY is superfluous.

John Viescas
TexanInParis

> On Oct 15, 2019, at 09:53, buzzerrookie <notifications@github.com> wrote:
> 

﻿
But without the last group by in Listing 5.015.sql, I can get the same query result as the query with Listing 5.015.sql.
with the last group by

SELECT C.CategoryDescription, P.ProductName, 
  SUM(OD.QuotedPrice * OD.QuantityOrdered) AS TotalSales
FROM Products AS P 
  INNER JOIN Order_Details AS OD 
     ON P.ProductNumber=OD.ProductNumber
  INNER JOIN Categories AS C
     ON C.CategoryID = P.CategoryID
  INNER JOIN Orders AS O
     ON O.OrderNumber = OD.OrderNumber
WHERE O.OrderDate BETWEEN '2015-10-01' AND '2015-12-31'
GROUP BY P.CategoryID, C.CategoryDescription, P.ProductName
HAVING SUM(OD.QuotedPrice * OD.QuantityOrdered) > 
  (SELECT AVG(SumCategory) 
   FROM 
     (SELECT P2.CategoryID, 
       SUM(OD2.QuotedPrice * OD2.QuantityOrdered) 
       AS SumCategory 
      FROM Products AS P2 
      INNER JOIN Order_Details AS OD2 
        ON P2.ProductNumber = OD2.ProductNumber 
      INNER JOIN Orders AS O2
        ON O2.OrderNumber = OD2.OrderNumber
      WHERE P2.CategoryID = P.CategoryID
      AND O2.OrderDate BETWEEN '2015-10-01' AND '2015-12-31'
      GROUP BY P2.CategoryID, P2.ProductNumber) AS S 
GROUP BY CategoryID)
ORDER BY CategoryDescription, ProductName;
 categorydescription |           productname            | totalsales
---------------------+----------------------------------+-------------
 Accessories         | Cycle-Doc Pro Repair Stand       |  32595.7600
 Accessories         | Dog Ear Aero-Flow Floor Pump     |  15539.1500
 Accessories         | Glide-O-Matic Cycling Helmet     |  23640.0000
 Accessories         | King Cobra Helmet                |  27847.2600
 Accessories         | Viscount CardioSport Sport Watch |  16469.7900
 Bikes               | GT RTS-2 Mountain Bike           | 527703.0000
 Bikes               | Trek 9000 Mountain Bike          | 954516.0000
 Car racks           | Ultimate Export 2G Car Rack      |  31014.0000
 Clothing            | StaDry Cycling Pants             |   8641.5600
 Components          | AeroFlo ATB Wheels               |  37709.2800
 Components          | Cosmic Elite Road Warrior Wheels |  32064.4500
 Components          | Eagle SA-120 Clipless Pedals     |  17003.8500
 Skateboards         | Viscount Skateboard              | 196964.3000
 Tires               | Ultra-2K Competition Tire        |   5216.2800
(14 rows)
without the last group by

SELECT C.CategoryDescription, P.ProductName, 
  SUM(OD.QuotedPrice * OD.QuantityOrdered) AS TotalSales
FROM Products AS P 
  INNER JOIN Order_Details AS OD 
     ON P.ProductNumber=OD.ProductNumber
  INNER JOIN Categories AS C
     ON C.CategoryID = P.CategoryID
  INNER JOIN Orders AS O
     ON O.OrderNumber = OD.OrderNumber
WHERE O.OrderDate BETWEEN '2015-10-01' AND '2015-12-31'
GROUP BY P.CategoryID, C.CategoryDescription, P.ProductName
HAVING SUM(OD.QuotedPrice * OD.QuantityOrdered) > 
  (SELECT AVG(SumCategory) 
   FROM 
     (SELECT P2.CategoryID, 
       SUM(OD2.QuotedPrice * OD2.QuantityOrdered) 
       AS SumCategory 
      FROM Products AS P2 
      INNER JOIN Order_Details AS OD2 
        ON P2.ProductNumber = OD2.ProductNumber 
      INNER JOIN Orders AS O2
        ON O2.OrderNumber = OD2.OrderNumber
      WHERE P2.CategoryID = P.CategoryID
      AND O2.OrderDate BETWEEN '2015-10-01' AND '2015-12-31'
      GROUP BY P2.CategoryID, P2.ProductNumber) AS S)
ORDER BY CategoryDescription, ProductName;
 categorydescription |           productname            | totalsales
---------------------+----------------------------------+-------------
 Accessories         | Cycle-Doc Pro Repair Stand       |  32595.7600
 Accessories         | Dog Ear Aero-Flow Floor Pump     |  15539.1500
 Accessories         | Glide-O-Matic Cycling Helmet     |  23640.0000
 Accessories         | King Cobra Helmet                |  27847.2600
 Accessories         | Viscount CardioSport Sport Watch |  16469.7900
 Bikes               | GT RTS-2 Mountain Bike           | 527703.0000
 Bikes               | Trek 9000 Mountain Bike          | 954516.0000
 Car racks           | Ultimate Export 2G Car Rack      |  31014.0000
 Clothing            | StaDry Cycling Pants             |   8641.5600
 Components          | AeroFlo ATB Wheels               |  37709.2800
 Components          | Cosmic Elite Road Warrior Wheels |  32064.4500
 Components          | Eagle SA-120 Clipless Pedals     |  17003.8500
 Skateboards         | Viscount Skateboard              | 196964.3000
 Tires               | Ultra-2K Competition Tire        |   5216.2800
(14 rows)

**Comment by buzzerrookie** [comment]
Sorry for misleading you, thanks !
